#!/usr/bin/env python3
"""Install genuine pinned Prek hooks with documented canonical execution.

Install the owning pinned upstream checker implementations faithfully.
The helper transforms only the real generated Prek pre-commit script and leaves
its actual checker, executable and arguments intact, then reconciles managed
Repro hooks. All integration controls use real tools/filesystem; no mocks.
"""
from __future__ import annotations
import argparse
import hashlib
import os
from pathlib import Path
import shutil
import stat
import subprocess
import sys
import tempfile

CONTRACT = "reprobuild.managed-hook.v1.pre-commit.434c2eeac4079591"
EXPORT = b"export PREK_NO_FAST_PATH=1\n"
DISPATCHER_SHA256 = "06cfcb59c42b99e9432c469f6bce7dc4fa5b0fa7c6f4f4e0548a1161233cf576"
ENGINE_SHA256 = "7be8236d8e91b646e7ba734f2a69c69e5081d77c49977edd944e33598c8e5d9a"
GENERATED = b"# File generated by prek: https://github.com/j178/prek\n"

def run(argv: list[str], cwd: Path) -> str:
    return subprocess.check_output(argv, cwd=cwd, text=True, stderr=subprocess.STDOUT).strip()

def selected_tool(name: str) -> str:
    found = shutil.which(name)
    if not found:
        raise RuntimeError(f"missing declared native tool: {name}")
    return str(Path(found).absolute())

def canonical_generated_body(body: bytes, prek: str) -> bytes:
    # Exact 0.3.11 template independently generated in an isolated real Git repo.
    template = b'#!/bin/sh\n# File generated by prek: https://github.com/j178/prek\n# ID: 182c10f181da4464a3eec51b83331688\n\nHERE="$(cd "$(dirname "$0")" && pwd)"\nPREK="/nix/store/ynj2jbamrgjfmaajlxfhnh1fhvwq0qzy-prek-0.3.11/bin/prek"\n\n# Check if the full path to prek is executable, otherwise fallback to PATH\nif [ ! -x "$PREK" ]; then\n    PREK="prek"\nfi\n\nexec "$PREK" hook-impl --hook-dir "$HERE" --script-version 4 --hook-type=pre-commit -- "$@"\n\n'
    selected = template.replace(b'PREK="/nix/store/ynj2jbamrgjfmaajlxfhnh1fhvwq0qzy-prek-0.3.11/bin/prek"', ('PREK="' + prek + '"').encode(), 1)
    if body != selected:
        raise RuntimeError("unexpected actual Prek 0.3.11 generated hook template")
    first, rest = body.split(b"\n", 1)
    return first + b"\n" + EXPORT + rest

def atomic_write(path: Path, data: bytes, mode: int) -> None:
    descriptor, filename = tempfile.mkstemp(prefix=".canonical-prek-", dir=path.parent)
    temporary = Path(filename)
    try:
        with os.fdopen(descriptor, "wb") as stream:
            stream.write(data)
            stream.flush()
            os.fsync(stream.fileno())
        temporary.chmod(mode)
        os.replace(temporary, path)
    finally:
        if temporary.exists():
            temporary.unlink()

def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repro", required=True, help="explicit measured matching managed-hook engine")
    args = parser.parse_args()
    root = Path.cwd().resolve()
    git = selected_tool("git")
    prek = selected_tool("prek")
    repro = Path(args.repro).absolute()
    if not repro.is_file() or not os.access(repro, os.X_OK):
        raise RuntimeError("missing selected matching Repro executable")
    if Path(run([git, "rev-parse", "--show-toplevel"], root)).resolve() != root:
        raise RuntimeError("run from actual owning repository root")
    config = root / ".pre-commit-config.yaml"
    if config.is_symlink() or not config.is_file():
        raise RuntimeError("missing owning portable standard config")
    if run([prek, "--version"], root) != "prek 0.3.11":
        raise RuntimeError("unqualified native Prek version")
    if hashlib.sha256(repro.read_bytes()).hexdigest() != ENGINE_SHA256:
        raise RuntimeError("unqualified managed engine bytes")
    if run([str(repro), "hooks", "protocol", "--require=2", "--hook-contract=" + CONTRACT], root) != "2":
        raise RuntimeError("matching managed hook protocol failed")
    git_dir_raw = Path(run([git, "rev-parse", "--absolute-git-dir"], root))
    for candidate in (git_dir_raw, *git_dir_raw.parents):
        if candidate.is_symlink():
            raise RuntimeError("symlink component in Git metadata path")
    git_dir = git_dir_raw.resolve()
    common_raw = Path(run([git, "rev-parse", "--git-common-dir"], root))
    common_lexical = root / common_raw if not common_raw.is_absolute() else common_raw
    for candidate in (common_lexical, *common_lexical.parents):
        if candidate.is_symlink():
            raise RuntimeError("symlink component in common Git metadata path")
    common = common_lexical.resolve()
    if git_dir != common or not common.is_relative_to(root):
        raise RuntimeError("shared/external Git hook ownership requires separate qualification")
    hooks = common / "hooks"
    # Check lexical components before resolve() can erase a symlink boundary.
    for candidate in (hooks, *hooks.parents):
        if candidate.is_symlink():
            raise RuntimeError("symlink component in owning hooks directory")
    if hooks.is_symlink() or (hooks.exists() and not hooks.is_dir()):
        raise RuntimeError("own hooks directory is symlink or non-directory")
    configured = subprocess.run([git, "config", "--get", "core.hooksPath"], cwd=root, text=True, capture_output=True)
    if configured.returncode not in (0, 1):
        raise RuntimeError("cannot inspect own hook path")
    if configured.returncode == 0:
        raw = Path(configured.stdout.strip())
        lexical = raw if raw.is_absolute() else root / raw
        for candidate in (lexical, *lexical.parents):
            if candidate.is_symlink():
                raise RuntimeError("symlink component in configured hooks path")
        resolved = (root / raw).resolve() if not raw.is_absolute() else raw.resolve()
        if resolved != hooks:
            raise RuntimeError("nonowning or unqualified hooks directory")
    actual_hooks = Path(run([git, "rev-parse", "--path-format=absolute", "--git-path", "hooks"], root))
    for candidate in (actual_hooks, *actual_hooks.parents):
        if candidate.is_symlink():
            raise RuntimeError("symlink component in effective hooks path")
    if actual_hooks.is_symlink() or actual_hooks.resolve() != hooks.resolve():
        raise RuntimeError("effective Git hooks path is not the owning directory")
    if actual_hooks.exists() and not actual_hooks.is_dir():
        raise RuntimeError("effective hooks path is non-directory")
    # Never silently omit a symlink from the preservation inventory.
    for entry in hooks.iterdir() if hooks.exists() else ():
        if entry.is_symlink():
            raise RuntimeError("symlink hook entry requires separate ownership review: " + entry.name)
    def push_inventory() -> dict[str, tuple[bytes, int]]:
        result = {}
        for entry in hooks.glob("pre-push*"):
            if entry.is_symlink() or not stat.S_ISREG(entry.lstat().st_mode):
                raise RuntimeError("nonregular pre-push entry: " + entry.name)
            result[entry.name] = (entry.read_bytes(), stat.S_IMODE(entry.stat().st_mode))
        return result
    original_pre_push = push_inventory()
    env = os.environ.copy()
    env["PREK_NO_FAST_PATH"] = "1"
    env["REPROBUILD_REPRO"] = str(repro)
    # The owning config requests system Python. Native interpreter/download
    # behavior must be qualified against this exact Prek version; the SDK
    # supplies its selected native Python and UV through PATH.
    existing = hooks / "pre-commit"
    if existing.is_symlink():
        raise RuntimeError("symlink pre-commit hook, including dangling link")
    if existing.exists():
        if existing.is_symlink() or not existing.is_file():
            raise RuntimeError("unowned existing pre-commit hook shape")
        previous = existing.read_bytes()
        if previous.startswith(b"#!/usr/bin/env sh\n# reprobuild hook dispatcher protocol=2\n"):
            if hashlib.sha256(previous).hexdigest() != DISPATCHER_SHA256:
                raise RuntimeError("unknown managed dispatcher body")
        else:
            canonical_generated_body(previous.replace(EXPORT, b"", 1), prek)
    legacy = hooks / "pre-commit.legacy"
    if legacy.is_symlink():
        raise RuntimeError("symlink legacy backup, including dangling link")
    if legacy.exists():
        if not legacy.is_file():
            raise RuntimeError("unowned legacy backup shape")
        # Never replace or silently execute an unknown installation backup.
        if not existing.exists() or legacy.read_bytes() != existing.read_bytes():
            raise RuntimeError("legacy backup requires independent ownership reconciliation")
    preserved = hooks / "pre-commit.repro-local"
    preserved_before = None
    if preserved.is_symlink():
        raise RuntimeError("symlink preserved hook, including dangling link")
    if preserved.exists():
        if preserved.is_symlink() or not preserved.is_file():
            raise RuntimeError("unowned preserved local hook shape")
        preserved_before = preserved.read_bytes()
        canonical_generated_body(preserved_before.replace(EXPORT, b"", 1), prek)
    hooks.mkdir(exist_ok=True)
    try:
        subprocess.run([prek, "install", "--install-hooks"], cwd=root, env=env, check=True)
        generated = hooks / "pre-commit"
        if generated.is_symlink() or not generated.is_file():
            raise RuntimeError("actual generated local pre-commit is not owned regular file")
        body = generated.read_bytes()
        mode = stat.S_IMODE(generated.stat().st_mode)
        if not mode & stat.S_IXUSR:
            raise RuntimeError("generated native hook is not executable")
        canonical = canonical_generated_body(body, prek)
        atomic_write(generated, canonical, mode)
        if preserved.is_symlink() or (preserved.exists() and not preserved.is_file()):
            raise RuntimeError("preserved local hook changed shape during installation")
        if preserved.exists() != (preserved_before is not None):
            raise RuntimeError("preserved local hook created or disappeared during installation")
        if preserved_before is not None:
            if preserved.read_bytes() != preserved_before:
                raise RuntimeError("preserved local hook changed during installation")
            backup = hooks / ("pre-commit.repro-local.backup-" + hashlib.sha256(preserved_before).hexdigest())
            if backup.is_symlink() or (backup.exists() and (not backup.is_file() or backup.read_bytes() != preserved_before)):
                raise RuntimeError("unowned preserved-template backup")
            if not backup.exists():
                atomic_write(backup, preserved_before, stat.S_IMODE(preserved.stat().st_mode))
            atomic_write(preserved, canonical, mode)
    finally:
        # Even installation/template failure must leave the managed dispatcher
        # reconciled; no commit is attempted on a failed canonical installation.
        subprocess.run([str(repro), "hooks", "ensure", "--vcs", "."], cwd=root, env=env, check=True)
        if push_inventory() != original_pre_push:
            raise RuntimeError("pre-push inventory/body/modes changed")
    local = hooks / "pre-commit.repro-local"
    if local.is_symlink() or local.read_bytes() != canonical:
        raise RuntimeError("reconciled local hook did not preserve canonical native script")
    if push_inventory() != original_pre_push:
        raise RuntimeError("pre-push inventory/body/modes changed")
    print("Canonical pinned hook installed; local bytes SHA256=" + hashlib.sha256(canonical).hexdigest())

if __name__ == "__main__":
    main()
